#!/usr/bin/env python3
"""Rebuild the WordPress/Elementor copies of the digital visiting card.

The Next.js page at src/app/save-contact is the source of truth. This script
extracts the markup from the production build, inlines the stylesheet, swaps the
Next-specific bits for placeholders, and writes the files a WordPress site needs.

Usage:
    npm run build
    python3 docs/save-contact/regenerate.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "save-contact"

BUILT_PAGE = ROOT / ".next" / "server" / "app" / "save-contact.html"
BUILT_VCARD = ROOT / ".next" / "server" / "app" / "save-contact" / "vcard.body"
CSS = ROOT / "src" / "app" / "save-contact" / "card.css"


def main() -> int:
    if not BUILT_PAGE.exists():
        print(f"error: {BUILT_PAGE.relative_to(ROOT)} not found — run `npm run build` first.")
        return 1

    page = BUILT_PAGE.read_text()
    css = CSS.read_text()

    match = re.search(r'<main class="tr-card">.*?</main>', page, re.S)
    if not match:
        print("error: could not find the card markup in the built page.")
        return 1
    markup = match.group(0)

    # Next's <img> carries /_next/image srcset URLs that mean nothing in WordPress.
    markup = re.sub(
        r"<img[^>]*class=\"tr-logo\"[^>]*>",
        '<img class="tr-logo" src="LOGO_URL_HERE" alt="Tricity Rides logo" '
        'width="74" height="74" decoding="async">',
        markup,
    )
    markup = markup.replace('href="/save-contact/vcard"', 'href="VCARD_URL_HERE"')
    # React hydration markers are inert but noise in a paste-in block.
    markup = markup.replace("<!--$-->", "").replace("<!--/$-->", "")

    widget = f"""<!--
  Tricity Rides — digital visiting card
  Paste this whole block into a single Elementor "HTML" widget.

  Before it works, replace the two placeholders:
    LOGO_URL_HERE  -> the Media Library URL of the logo icon PNG
    VCARD_URL_HERE -> the URL of tricity-rides-gurdeep-sharma.vcf

  Both are explained in docs/save-contact/README.md.
  Generated by docs/save-contact/regenerate.py — do not hand-edit.
-->
<style>
{css}</style>

{markup}
"""
    (OUT / "elementor-widget.html").write_text(widget)

    standalone = f"""<!doctype html>
<html lang="en-IN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Tricity Rides | Save Contact</title>
<meta name="description" content="Save Tricity Rides contact details and book local, airport and outstation taxi services in Chandigarh, Mohali and Zirakpur.">
<link rel="canonical" href="https://tricityrides.in/save-contact/">
<meta name="theme-color" content="#0f2e4a">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Tricity Rides">
<meta property="og:title" content="Tricity Rides — Your Journey, Our Priority">
<meta property="og:description" content="Save our contact and book local, airport and outstation taxis across Chandigarh, Mohali and Zirakpur.">
<meta property="og:url" content="https://tricityrides.in/save-contact/">
<meta property="og:image" content="OG_IMAGE_URL_HERE">
<meta name="twitter:card" content="summary_large_image">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
body {{ margin: 0; background: #eef3f8; }}
{css}</style>
</head>
<body>
{markup}
</body>
</html>
"""
    (OUT / "standalone.html").write_text(standalone)

    if BUILT_VCARD.exists():
        (OUT / "tricity-rides-gurdeep-sharma.vcf").write_bytes(BUILT_VCARD.read_bytes())

    for name in ("elementor-widget.html", "standalone.html", "tricity-rides-gurdeep-sharma.vcf"):
        path = OUT / name
        print(f"wrote {path.relative_to(ROOT)}  ({path.stat().st_size} bytes)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
